<?php

return [
    'motion_fields' => [
        ['code' => 'convict_firstname', 'name' => 'Imię skazanego', 'name_lang' => 'attributes.convict_firstname'],
        ['code' => 'convict_lastname', 'name' => 'Nazwisko skazanego', 'name_lang' => 'attributes.convict_lastname'],
        ['code' => 'convict_family_lastname', 'name' => 'Nazwisko rodowe skazanego', 'name_lang' => 'attributes.convict_family_lastname'],
        ['code' => 'convict_father_firstname', 'name' => 'Imię ojca skazanego', 'name_lang' => 'attributes.convict_father_firstname'],
        ['code' => 'convict_mother_firstname', 'name' => 'Imię matki skazanego', 'name_lang' => 'attributes.convict_mother_firstname'],
        ['code' => 'convict_mother_family_lastname', 'name' => 'Nazwisko rodowe matki', 'name_lang' => 'attributes.convict_mother_family_lastname'],
        ['code' => 'convict_date_birthday', 'name' => 'Data urodzenia skazanego', 'name_lang' => 'attributes.convict_date_birthday'],
        ['code' => 'convict_place_birthday', 'name' => 'Miejsce urodzenia skazanego', 'name_lang' => 'attributes.convict_place_birthday'],
        ['code' => 'convict_pesel', 'name' => 'PESEL skazanego', 'name_lang' => 'attributes.convict_pesel'],
        ['code' => 'convict_identity_card', 'name' => 'Seria i numer dowodu osobistego skazanego', 'name_lang' => 'attributes.convict_identity_card'],
        ['code' => 'convict_phone', 'name' => 'Numer telefonu', 'name_lang' => 'attributes.convict_phone'],
        ['code' => 'convict_address_street', 'name' => 'Ulica', 'name_lang' => 'attributes.convict_address_street'],
        ['code' => 'convict_address_street_number_building', 'name' => 'Nr budynku', 'name_lang' => 'attributes.convict_address_street_number_building'],
        ['code' => 'convict_address_street_number_apartament', 'name' => 'Nr mieszkania', 'name_lang' => 'attributes.convict_address_street_number_apartament'],
        ['code' => 'convict_address_postal_code', 'name' => 'Kod pocztowy', 'name_lang' => 'attributes.convict_address_postal_code'],
        ['code' => 'convict_address_city', 'name' => 'Miasto', 'name_lang' => 'attributes.convict_address_city'],
        ['code' => 'convict_correctional_facility', 'name' => 'Zakład karny', 'name_lang' => 'attributes.convict_correctional_facility'],
        ['code' => 'penalty_court', 'name' => 'Sąd', 'name_lang' => 'attributes.penalty_court'],
        ['code' => 'penalty_date', 'name' => 'Data wydania wyroku lub postanowienia', 'name_lang' => 'attributes.penalty_date'],
        ['code' => 'penalty_signature', 'name' => 'Sygnatura', 'name_lang' => 'attributes.penalty_signature'],
        ['code' => 'penalty_size', 'name' => 'Wymiar kary', 'name_lang' => 'attributes.penalty_size'],
        ['code' => 'is_penalty_previous', 'name' => 'Czy wobec skazanego orzekana była w przeszłości kara pozbawienia wolności', 'name_lang' => 'attributes.is_penalty_previous'],
        ['code' => 'convict_behaviour', 'name' => 'Zachowanie skazanego', 'name_lang' => 'attributes.convict_behaviour'],
        ['code' => 'convict_employment', 'name' => 'Informacje o zatrudnieniu', 'name_lang' => 'attributes.convict_employment'],
        ['code' => 'supervision_schedule', 'name' => 'Harmonogram dozoru', 'name_lang' => 'attributes.supervision_schedule'],
        ['code' => 'convict_address', 'name' => 'Adres, pod którym skazany będzie przebywał w czasie odbywania kary', 'name_lang' => 'convict_address'],
        ['code' => 'trial_date', 'name' => 'Data rozprawy', 'name_lang' => 'trial_date'],
        ['code' => 'trial_time', 'name' => 'Godzina rozprawy', 'name_lang' => 'trial_time'],
        ['code' => 'contact_phone_time', 'name' => 'Oczekiwana godzina telefonu', 'name_lang' => 'contact_phone_time'],
        ['code' => 'note', 'name' => 'Uwagi (opis sprawy)', 'name_lang' => 'note'],
        ['code' => 'penalty_delay_mental_illness', 'name' => 'Choroba psychiczna', 'name_lang' => 'penalty_delay_mental_illness'],
        ['code' => 'penalty_delay_other_illness', 'name' => 'Inne choroby', 'name_lang' => 'penalty_delay_other_illness'],
        ['code' => 'is_convict_woman_child', 'name' => 'Czy skazana jest kobietą ciężarną lub kobietą samotnie wychowującą dziecko?', 'name_lang' => 'is_convict_woman_child'],
        ['code' => 'penalty_delay_family_heavy', 'name' => 'Ciężkie skutki dla skazanego i jego rodziny', 'name_lang' => 'penalty_delay_family_heavy'],
        ['code' => 'penalty_delay_residence', 'name' => 'Sytuacja mieszkaniowa skazanego i jego rodziny', 'name_lang' => 'penalty_delay_residence'],
        ['code' => 'penalty_delay_family', 'name' => 'Sytuacja rodzinna skazanego', 'name_lang' => 'penalty_delay_family'],
        ['code' => 'penalty_delay_finance', 'name' => 'Sytuacja finansowa skazanego i jego rodziny', 'name_lang' => 'penalty_delay_finance'],
        ['code' => 'content', 'name' => 'Wiadomość', 'name_lang' => 'content'],
        ['code' => 'content_title', 'name' => 'Temat wiadomości', 'name_lang' => 'content_title']
    ]
];
